name: PowerShell Lint

on:
  push:
    paths:
      - '**.ps1'
  pull_request:
    paths:
      - '**.ps1'

jobs:
  lint:
    name: PowerShell Syntax Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run PowerShell script analysis
      shell: pwsh
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
        Invoke-ScriptAnalyzer -Path './Scripts/*.ps1' -Recurse -Severity Warning
